spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/auth_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=validate

app.jwtSecret=${JWT_SECRET:change_this_to_a_long_random_string}
app.jwtExpirationMs=28800000
server.port=4000
