# NFT environment properties for pg-service
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
server.port=${SERVER_PORT:4001}

# Actuator exposure - enable for NFT for testing, but secure in infra
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=when_authorized
