spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://pg-db:3306/pg_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rootpw}

spring.jpa.hibernate.ddl-auto=update
server.port=4001

# Actuator / Prometheus
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
